### ISSUE TITLE
Excessive tick times

### ISSUE THREAD

**Issue by Nexela** [arlyoneel/factorio-lydevgui#3]
Excessive tick times
Should be re-written to fire maybe at most every 20 ticks

**Comment by arlyoneel** [comment]
Yes it has expensive calls per tick, this is because im using a lot load(), thanks to this design is easily extendable with new fields. 

When i think there is no fields to add, will translate all load() calls to player.path.to.field

This is not for daily use, is for testing stuff, anyway i'll try improve some of the current functions.

**Comment by Nexela** [comment]
I agree about the not for daily use, but the excessive times can make it hard to do development on other mods :)

The fastest way to hand this would be to wrap everything in your on tick with something like  
if event.tick % 30 == 0 then
--everything here
end

30 ticks should be plenty of time between updating player.selected

**Comment by arlyoneel** [comment]
ty for the suggestion, ill try to add something like that, keep in mind that this is mi first mod and my first lua programming stuff

can you suggest me some expensive per tick mods to test?
