### ISSUE TITLE
Generic Issues 

### ISSUE THREAD

**Issue by Nexela** [arlyoneel/factorio-lydevgui#4]
Missing backer_name
Missing unit_number

Stack portion of GUI should be re-written to not show if not item-entity

**Comment by Nexela** [comment]
Missing entity.ghost_name
Missing entity.ghost_type

**Comment by arlyoneel** [comment]
ty, will be added soon.

**Comment by Nexela** [comment]
gui.top should follow unofficial standards   (Most of the top mods are pretty close to this)

.top should be button 32x32 - any windows opened from gui.top should open on gui.left or gui.center

This keeps gui.top clear and organized.

**Comment by arlyoneel** [comment]
"Stack portion of GUI should be re-written to not show if not item-entity" is already fixed in 2.x,

then i dont understand what are you talking about gui positions, yes is huge and ugly the button, and is on top, then the window opened from that button is gui.center, and variables are gui.left.

what of all of those dont follow the "standars"?, and there is a thread talking about that?, ty!

**Comment by Nexela** [comment]
> what of all of those dont follow the "standars"?, and there is a thread talking about that?, ty!

Mostly related to the height and width of a mods "main" button.   A while back I ran a push for consistency and most of the popular mods complied

I'll try and dig up some screen shots and conversations soon. Basicly what it boils down to is all the mods using gui.top limit themselves to 32px in height, and 32px in width (or the minimal width needed)
![buttons](https://cloud.githubusercontent.com/assets/13972192/21917545/7d520fbc-d916-11e6-9931-cffffe558104.png)

This is an example of a "mostly" consistent gui.top layout

**Comment by arlyoneel** [comment]
in last version 0.2.4 i leave just the button on top, added ghost_name, and ghost type

**Comment by arlyoneel** [comment]
> Missing backer_name
> Missing unit_number

added in 0.2.5
